# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AMaDiAUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AMaDiA_Main_Window(object):
    def setupUi(self, AMaDiA_Main_Window):
        AMaDiA_Main_Window.setObjectName("AMaDiA_Main_Window")
        AMaDiA_Main_Window.resize(840, 634)
        AMaDiA_Main_Window.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(AMaDiA_Main_Window)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.Tab_1_Calculator = QtWidgets.QWidget()
        self.Tab_1_Calculator.setAutoFillBackground(True)
        self.Tab_1_Calculator.setObjectName("Tab_1_Calculator")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Tab_1_Calculator)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Tab_1_Calculator_History = QtWidgets.QListWidget(self.Tab_1_Calculator)
        self.Tab_1_Calculator_History.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.Tab_1_Calculator_History.setObjectName("Tab_1_Calculator_History")
        self.gridLayout_2.addWidget(self.Tab_1_Calculator_History, 0, 0, 1, 1)
        self.Tab_1_Calculator_InputField = QtWidgets.QLineEdit(self.Tab_1_Calculator)
        self.Tab_1_Calculator_InputField.setObjectName("Tab_1_Calculator_InputField")
        self.gridLayout_2.addWidget(self.Tab_1_Calculator_InputField, 1, 0, 1, 1)
        self.tabWidget.addTab(self.Tab_1_Calculator, "")
        self.Tab_2_LaTeX = QtWidgets.QWidget()
        self.Tab_2_LaTeX.setAutoFillBackground(True)
        self.Tab_2_LaTeX.setObjectName("Tab_2_LaTeX")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Tab_2_LaTeX)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Tab_2_LaTeX_ConvertButton = QtWidgets.QPushButton(self.Tab_2_LaTeX)
        self.Tab_2_LaTeX_ConvertButton.setObjectName("Tab_2_LaTeX_ConvertButton")
        self.gridLayout_3.addWidget(self.Tab_2_LaTeX_ConvertButton, 1, 1, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.Tab_2_LaTeX_LowerSplitter = QtWidgets.QSplitter(self.Tab_2_LaTeX)
        self.Tab_2_LaTeX_LowerSplitter.setOrientation(QtCore.Qt.Vertical)
        self.Tab_2_LaTeX_LowerSplitter.setObjectName("Tab_2_LaTeX_LowerSplitter")
        self.Tab_2_LaTeX_UpperSplitter = QtWidgets.QSplitter(self.Tab_2_LaTeX_LowerSplitter)
        self.Tab_2_LaTeX_UpperSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.Tab_2_LaTeX_UpperSplitter.setObjectName("Tab_2_LaTeX_UpperSplitter")
        self.Tab_2_LaTeX_History = QtWidgets.QListWidget(self.Tab_2_LaTeX_UpperSplitter)
        self.Tab_2_LaTeX_History.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.Tab_2_LaTeX_History.setObjectName("Tab_2_LaTeX_History")
        self.layoutWidget = QtWidgets.QWidget(self.Tab_2_LaTeX_UpperSplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.Tab_2_LaTeX_verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.Tab_2_LaTeX_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.Tab_2_LaTeX_verticalLayout.setObjectName("Tab_2_LaTeX_verticalLayout")
        self.Tab_2_LaTeX_scrollArea = QtWidgets.QScrollArea(self.layoutWidget)
        self.Tab_2_LaTeX_scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Tab_2_LaTeX_scrollArea.setWidgetResizable(True)
        self.Tab_2_LaTeX_scrollArea.setObjectName("Tab_2_LaTeX_scrollArea")
        self.Tab_2_LaTeX_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.Tab_2_LaTeX_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 270, 206))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab_2_LaTeX_scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.Tab_2_LaTeX_scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.Tab_2_LaTeX_scrollAreaWidgetContents.setObjectName("Tab_2_LaTeX_scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Tab_2_LaTeX_scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Tab_2_LaTeX_Viewer = MplWidget(self.Tab_2_LaTeX_scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab_2_LaTeX_Viewer.sizePolicy().hasHeightForWidth())
        self.Tab_2_LaTeX_Viewer.setSizePolicy(sizePolicy)
        self.Tab_2_LaTeX_Viewer.setObjectName("Tab_2_LaTeX_Viewer")
        self.gridLayout_4.addWidget(self.Tab_2_LaTeX_Viewer, 0, 0, 1, 1)
        self.Tab_2_LaTeX_scrollArea.setWidget(self.Tab_2_LaTeX_scrollAreaWidgetContents)
        self.Tab_2_LaTeX_verticalLayout.addWidget(self.Tab_2_LaTeX_scrollArea)
        self.Tab_2_LaTeX_LaTeXOutput = QtWidgets.QLineEdit(self.layoutWidget)
        self.Tab_2_LaTeX_LaTeXOutput.setObjectName("Tab_2_LaTeX_LaTeXOutput")
        self.Tab_2_LaTeX_verticalLayout.addWidget(self.Tab_2_LaTeX_LaTeXOutput)
        self.Tab_2_LaTeX_InputField = QtWidgets.QTextEdit(self.Tab_2_LaTeX_LowerSplitter)
        self.Tab_2_LaTeX_InputField.setObjectName("Tab_2_LaTeX_InputField")
        self.gridLayout_3.addWidget(self.Tab_2_LaTeX_LowerSplitter, 0, 0, 1, 2)
        self.tabWidget.addTab(self.Tab_2_LaTeX, "")
        self.Tab_3_2D_Plot = QtWidgets.QWidget()
        self.Tab_3_2D_Plot.setObjectName("Tab_3_2D_Plot")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.Tab_3_2D_Plot)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.Tab_3_2D_Plot_gridLayout_2 = QtWidgets.QGridLayout()
        self.Tab_3_2D_Plot_gridLayout_2.setObjectName("Tab_3_2D_Plot_gridLayout_2")
        self.Tab_3_2D_Plot_From_Spinbox = QtWidgets.QDoubleSpinBox(self.Tab_3_2D_Plot)
        self.Tab_3_2D_Plot_From_Spinbox.setDecimals(5)
        self.Tab_3_2D_Plot_From_Spinbox.setMinimum(-1000000.0)
        self.Tab_3_2D_Plot_From_Spinbox.setMaximum(1000000.0)
        self.Tab_3_2D_Plot_From_Spinbox.setProperty("value", -5.0)
        self.Tab_3_2D_Plot_From_Spinbox.setObjectName("Tab_3_2D_Plot_From_Spinbox")
        self.Tab_3_2D_Plot_gridLayout_2.addWidget(self.Tab_3_2D_Plot_From_Spinbox, 2, 1, 1, 1)
        self.Tab_3_2D_Plot_Label_from = QtWidgets.QLabel(self.Tab_3_2D_Plot)
        self.Tab_3_2D_Plot_Label_from.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Tab_3_2D_Plot_Label_from.setObjectName("Tab_3_2D_Plot_Label_from")
        self.Tab_3_2D_Plot_gridLayout_2.addWidget(self.Tab_3_2D_Plot_Label_from, 2, 0, 1, 1)
        self.Tab_3_2D_Plot_Label_Steps = QtWidgets.QLabel(self.Tab_3_2D_Plot)
        self.Tab_3_2D_Plot_Label_Steps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Tab_3_2D_Plot_Label_Steps.setObjectName("Tab_3_2D_Plot_Label_Steps")
        self.Tab_3_2D_Plot_gridLayout_2.addWidget(self.Tab_3_2D_Plot_Label_Steps, 2, 4, 1, 1)
        self.Tab_3_2D_Plot_Formula_Field = QtWidgets.QLineEdit(self.Tab_3_2D_Plot)
        self.Tab_3_2D_Plot_Formula_Field.setObjectName("Tab_3_2D_Plot_Formula_Field")
        self.Tab_3_2D_Plot_gridLayout_2.addWidget(self.Tab_3_2D_Plot_Formula_Field, 3, 0, 1, 9)
        self.Tab_3_2D_Plot_To_Spinbox = QtWidgets.QDoubleSpinBox(self.Tab_3_2D_Plot)
        self.Tab_3_2D_Plot_To_Spinbox.setDecimals(5)
        self.Tab_3_2D_Plot_To_Spinbox.setMinimum(-1000000.0)
        self.Tab_3_2D_Plot_To_Spinbox.setMaximum(1000000.0)
        self.Tab_3_2D_Plot_To_Spinbox.setProperty("value", 5.0)
        self.Tab_3_2D_Plot_To_Spinbox.setObjectName("Tab_3_2D_Plot_To_Spinbox")
        self.Tab_3_2D_Plot_gridLayout_2.addWidget(self.Tab_3_2D_Plot_To_Spinbox, 2, 3, 1, 1)
        self.Tab_3_2D_Plot_Label_to = QtWidgets.QLabel(self.Tab_3_2D_Plot)
        self.Tab_3_2D_Plot_Label_to.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Tab_3_2D_Plot_Label_to.setObjectName("Tab_3_2D_Plot_Label_to")
        self.Tab_3_2D_Plot_gridLayout_2.addWidget(self.Tab_3_2D_Plot_Label_to, 2, 2, 1, 1)
        self.Tab_3_2D_Plot_Button_Plot = QtWidgets.QPushButton(self.Tab_3_2D_Plot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab_3_2D_Plot_Button_Plot.sizePolicy().hasHeightForWidth())
        self.Tab_3_2D_Plot_Button_Plot.setSizePolicy(sizePolicy)
        self.Tab_3_2D_Plot_Button_Plot.setObjectName("Tab_3_2D_Plot_Button_Plot")
        self.Tab_3_2D_Plot_gridLayout_2.addWidget(self.Tab_3_2D_Plot_Button_Plot, 2, 8, 1, 1)
        self.Tab_3_2D_Plot_splitter = QtWidgets.QSplitter(self.Tab_3_2D_Plot)
        self.Tab_3_2D_Plot_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.Tab_3_2D_Plot_splitter.setObjectName("Tab_3_2D_Plot_splitter")
        self.layoutWidget1 = QtWidgets.QWidget(self.Tab_3_2D_Plot_splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.Tab_3_2D_Plot_gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.Tab_3_2D_Plot_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.Tab_3_2D_Plot_gridLayout.setObjectName("Tab_3_2D_Plot_gridLayout")
        self.Tab_3_2D_Plot_Axis_ratio_Checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.Tab_3_2D_Plot_Axis_ratio_Checkbox.setObjectName("Tab_3_2D_Plot_Axis_ratio_Checkbox")
        self.Tab_3_2D_Plot_gridLayout.addWidget(self.Tab_3_2D_Plot_Axis_ratio_Checkbox, 1, 0, 1, 1)
        self.Tab_3_2D_Plot_History = QtWidgets.QListWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab_3_2D_Plot_History.sizePolicy().hasHeightForWidth())
        self.Tab_3_2D_Plot_History.setSizePolicy(sizePolicy)
        self.Tab_3_2D_Plot_History.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.Tab_3_2D_Plot_History.setObjectName("Tab_3_2D_Plot_History")
        self.Tab_3_2D_Plot_gridLayout.addWidget(self.Tab_3_2D_Plot_History, 0, 0, 1, 5)
        self.Tab_3_2D_Plot_Draw_Grid_Checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.Tab_3_2D_Plot_Draw_Grid_Checkbox.setChecked(True)
        self.Tab_3_2D_Plot_Draw_Grid_Checkbox.setObjectName("Tab_3_2D_Plot_Draw_Grid_Checkbox")
        self.Tab_3_2D_Plot_gridLayout.addWidget(self.Tab_3_2D_Plot_Draw_Grid_Checkbox, 2, 0, 1, 1)
        self.Tab_3_2D_Plot_ScrollArea = QtWidgets.QScrollArea(self.Tab_3_2D_Plot_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab_3_2D_Plot_ScrollArea.sizePolicy().hasHeightForWidth())
        self.Tab_3_2D_Plot_ScrollArea.setSizePolicy(sizePolicy)
        self.Tab_3_2D_Plot_ScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Tab_3_2D_Plot_ScrollArea.setWidgetResizable(True)
        self.Tab_3_2D_Plot_ScrollArea.setObjectName("Tab_3_2D_Plot_ScrollArea")
        self.Tab_3_2D_Plot_ScrollArea_Layout = QtWidgets.QWidget()
        self.Tab_3_2D_Plot_ScrollArea_Layout.setGeometry(QtCore.QRect(0, 0, 531, 446))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab_3_2D_Plot_ScrollArea_Layout.sizePolicy().hasHeightForWidth())
        self.Tab_3_2D_Plot_ScrollArea_Layout.setSizePolicy(sizePolicy)
        self.Tab_3_2D_Plot_ScrollArea_Layout.setObjectName("Tab_3_2D_Plot_ScrollArea_Layout")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Tab_3_2D_Plot_ScrollArea_Layout)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Tab_3_2D_Plot_Display = MplWidget(self.Tab_3_2D_Plot_ScrollArea_Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab_3_2D_Plot_Display.sizePolicy().hasHeightForWidth())
        self.Tab_3_2D_Plot_Display.setSizePolicy(sizePolicy)
        self.Tab_3_2D_Plot_Display.setObjectName("Tab_3_2D_Plot_Display")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Tab_3_2D_Plot_Display)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6.addWidget(self.Tab_3_2D_Plot_Display, 0, 0, 1, 1)
        self.Tab_3_2D_Plot_ScrollArea.setWidget(self.Tab_3_2D_Plot_ScrollArea_Layout)
        self.Tab_3_2D_Plot_gridLayout_2.addWidget(self.Tab_3_2D_Plot_splitter, 0, 0, 1, 9)
        self.Tab_3_2D_Plot_Button_Clear = QtWidgets.QPushButton(self.Tab_3_2D_Plot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab_3_2D_Plot_Button_Clear.sizePolicy().hasHeightForWidth())
        self.Tab_3_2D_Plot_Button_Clear.setSizePolicy(sizePolicy)
        self.Tab_3_2D_Plot_Button_Clear.setObjectName("Tab_3_2D_Plot_Button_Clear")
        self.Tab_3_2D_Plot_gridLayout_2.addWidget(self.Tab_3_2D_Plot_Button_Clear, 2, 7, 1, 1)
        self.Tab_3_2D_Plot_Steps_Spinbox = QtWidgets.QSpinBox(self.Tab_3_2D_Plot)
        self.Tab_3_2D_Plot_Steps_Spinbox.setMinimum(1)
        self.Tab_3_2D_Plot_Steps_Spinbox.setMaximum(100000)
        self.Tab_3_2D_Plot_Steps_Spinbox.setProperty("value", 1000)
        self.Tab_3_2D_Plot_Steps_Spinbox.setObjectName("Tab_3_2D_Plot_Steps_Spinbox")
        self.Tab_3_2D_Plot_gridLayout_2.addWidget(self.Tab_3_2D_Plot_Steps_Spinbox, 2, 5, 1, 1)
        self.Tab_3_2D_Plot_Steps_Checkbox = QtWidgets.QCheckBox(self.Tab_3_2D_Plot)
        self.Tab_3_2D_Plot_Steps_Checkbox.setChecked(False)
        self.Tab_3_2D_Plot_Steps_Checkbox.setObjectName("Tab_3_2D_Plot_Steps_Checkbox")
        self.Tab_3_2D_Plot_gridLayout_2.addWidget(self.Tab_3_2D_Plot_Steps_Checkbox, 2, 6, 1, 1)
        self.gridLayout_8.addLayout(self.Tab_3_2D_Plot_gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Tab_3_2D_Plot, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.Font_Size_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.Font_Size_spinBox.setMinimum(5)
        self.Font_Size_spinBox.setMaximum(25)
        self.Font_Size_spinBox.setProperty("value", 9)
        self.Font_Size_spinBox.setObjectName("Font_Size_spinBox")
        self.gridLayout.addWidget(self.Font_Size_spinBox, 0, 1, 1, 1)
        AMaDiA_Main_Window.setCentralWidget(self.centralwidget)
        self.Menubar_Main = QtWidgets.QMenuBar(AMaDiA_Main_Window)
        self.Menubar_Main.setGeometry(QtCore.QRect(0, 0, 840, 21))
        self.Menubar_Main.setObjectName("Menubar_Main")
        self.Menubar_Main_Options = QtWidgets.QMenu(self.Menubar_Main)
        self.Menubar_Main_Options.setObjectName("Menubar_Main_Options")
        AMaDiA_Main_Window.setMenuBar(self.Menubar_Main)
        self.statusbar = QtWidgets.QStatusBar(AMaDiA_Main_Window)
        self.statusbar.setObjectName("statusbar")
        AMaDiA_Main_Window.setStatusBar(self.statusbar)
        self.Menubar_Main_Options_action_Reload_Modules = QtWidgets.QAction(AMaDiA_Main_Window)
        self.Menubar_Main_Options_action_Reload_Modules.setObjectName("Menubar_Main_Options_action_Reload_Modules")
        self.Menubar_Main_Options_action_Advanced_Mode = QtWidgets.QAction(AMaDiA_Main_Window)
        self.Menubar_Main_Options_action_Advanced_Mode.setCheckable(True)
        self.Menubar_Main_Options_action_Advanced_Mode.setObjectName("Menubar_Main_Options_action_Advanced_Mode")
        self.Menubar_Main_Options_action_Eval_Functions = QtWidgets.QAction(AMaDiA_Main_Window)
        self.Menubar_Main_Options_action_Eval_Functions.setCheckable(True)
        self.Menubar_Main_Options_action_Eval_Functions.setChecked(True)
        self.Menubar_Main_Options_action_Eval_Functions.setObjectName("Menubar_Main_Options_action_Eval_Functions")
        self.Menubar_Main_Options.addAction(self.Menubar_Main_Options_action_Reload_Modules)
        self.Menubar_Main_Options.addAction(self.Menubar_Main_Options_action_Advanced_Mode)
        self.Menubar_Main_Options.addAction(self.Menubar_Main_Options_action_Eval_Functions)
        self.Menubar_Main.addAction(self.Menubar_Main_Options.menuAction())

        self.retranslateUi(AMaDiA_Main_Window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AMaDiA_Main_Window)
        AMaDiA_Main_Window.setTabOrder(self.Font_Size_spinBox, self.tabWidget)
        AMaDiA_Main_Window.setTabOrder(self.tabWidget, self.Tab_1_Calculator_History)
        AMaDiA_Main_Window.setTabOrder(self.Tab_1_Calculator_History, self.Tab_1_Calculator_InputField)
        AMaDiA_Main_Window.setTabOrder(self.Tab_1_Calculator_InputField, self.Tab_2_LaTeX_InputField)
        AMaDiA_Main_Window.setTabOrder(self.Tab_2_LaTeX_InputField, self.Tab_2_LaTeX_ConvertButton)
        AMaDiA_Main_Window.setTabOrder(self.Tab_2_LaTeX_ConvertButton, self.Tab_2_LaTeX_LaTeXOutput)
        AMaDiA_Main_Window.setTabOrder(self.Tab_2_LaTeX_LaTeXOutput, self.Tab_2_LaTeX_History)
        AMaDiA_Main_Window.setTabOrder(self.Tab_2_LaTeX_History, self.Tab_2_LaTeX_scrollArea)
        AMaDiA_Main_Window.setTabOrder(self.Tab_2_LaTeX_scrollArea, self.Tab_3_2D_Plot_Formula_Field)
        AMaDiA_Main_Window.setTabOrder(self.Tab_3_2D_Plot_Formula_Field, self.Tab_3_2D_Plot_Button_Plot)
        AMaDiA_Main_Window.setTabOrder(self.Tab_3_2D_Plot_Button_Plot, self.Tab_3_2D_Plot_Button_Clear)
        AMaDiA_Main_Window.setTabOrder(self.Tab_3_2D_Plot_Button_Clear, self.Tab_3_2D_Plot_Axis_ratio_Checkbox)
        AMaDiA_Main_Window.setTabOrder(self.Tab_3_2D_Plot_Axis_ratio_Checkbox, self.Tab_3_2D_Plot_Draw_Grid_Checkbox)
        AMaDiA_Main_Window.setTabOrder(self.Tab_3_2D_Plot_Draw_Grid_Checkbox, self.Tab_3_2D_Plot_From_Spinbox)
        AMaDiA_Main_Window.setTabOrder(self.Tab_3_2D_Plot_From_Spinbox, self.Tab_3_2D_Plot_To_Spinbox)
        AMaDiA_Main_Window.setTabOrder(self.Tab_3_2D_Plot_To_Spinbox, self.Tab_3_2D_Plot_Steps_Spinbox)
        AMaDiA_Main_Window.setTabOrder(self.Tab_3_2D_Plot_Steps_Spinbox, self.Tab_3_2D_Plot_Steps_Checkbox)
        AMaDiA_Main_Window.setTabOrder(self.Tab_3_2D_Plot_Steps_Checkbox, self.Tab_3_2D_Plot_History)
        AMaDiA_Main_Window.setTabOrder(self.Tab_3_2D_Plot_History, self.Tab_3_2D_Plot_ScrollArea)

    def retranslateUi(self, AMaDiA_Main_Window):
        _translate = QtCore.QCoreApplication.translate
        AMaDiA_Main_Window.setWindowTitle(_translate("AMaDiA_Main_Window", "AMaDiA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_1_Calculator), _translate("AMaDiA_Main_Window", "Calculator"))
        self.Tab_2_LaTeX_ConvertButton.setText(_translate("AMaDiA_Main_Window", "Convert"))
        self.Tab_2_LaTeX_InputField.setPlaceholderText(_translate("AMaDiA_Main_Window", "Add Mathematical Expression to be Converted to LaTeX"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_2_LaTeX), _translate("AMaDiA_Main_Window", "LaTeX"))
        self.Tab_3_2D_Plot_Label_from.setText(_translate("AMaDiA_Main_Window", "From"))
        self.Tab_3_2D_Plot_Label_Steps.setText(_translate("AMaDiA_Main_Window", "Steps"))
        self.Tab_3_2D_Plot_Label_to.setText(_translate("AMaDiA_Main_Window", "To"))
        self.Tab_3_2D_Plot_Button_Plot.setText(_translate("AMaDiA_Main_Window", "Plot"))
        self.Tab_3_2D_Plot_Axis_ratio_Checkbox.setText(_translate("AMaDiA_Main_Window", "1:1 axis ratio"))
        self.Tab_3_2D_Plot_Draw_Grid_Checkbox.setText(_translate("AMaDiA_Main_Window", "Draw Grid"))
        self.Tab_3_2D_Plot_Button_Clear.setText(_translate("AMaDiA_Main_Window", "Clear"))
        self.Tab_3_2D_Plot_Steps_Checkbox.setText(_translate("AMaDiA_Main_Window", "per unit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_3_2D_Plot), _translate("AMaDiA_Main_Window", "2D Plot"))
        self.Font_Size_spinBox.setToolTip(_translate("AMaDiA_Main_Window", "Font Size"))
        self.Menubar_Main_Options.setTitle(_translate("AMaDiA_Main_Window", "O&ptions"))
        self.Menubar_Main_Options_action_Reload_Modules.setText(_translate("AMaDiA_Main_Window", "Reload Modules"))
        self.Menubar_Main_Options_action_Advanced_Mode.setText(_translate("AMaDiA_Main_Window", "Advanced Mode"))
        self.Menubar_Main_Options_action_Eval_Functions.setText(_translate("AMaDiA_Main_Window", "Eval Functions"))

from AMaDiA_Widgets import MplWidget
