name: Slycot from source

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout python-control
      uses: actions/checkout@v3
      with:
        path: python-control
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Python dependencies and test tools
      run: pip install -v './python-control[test]'

    - name: Checkout Slycot
      uses: actions/checkout@v3
      with:
        repository: python-control/Slycot
        submodules: recursive
        fetch-depth: 0
        path: slycot
    - name: Install slycot from source
      env:
        BLA_VENDOR: Generic
        CMAKE_GENERATOR: Unix Makefiles
      working-directory: slycot
      run: |
        # Install compilers, libraries, and development environment
        sudo apt-get -y install gfortran cmake --fix-missing
        sudo apt-get -y install libblas-dev liblapack-dev

        # Compile and install slycot
        pip install -v .

    - name: Test with pytest
      working-directory: python-control
      run: pytest -v control/tests
