name: Conda-based pytest

on: [push, pull_request]

jobs:
  test-linux-conda:
    name: >
      Py${{ matrix.python-version }};
      ${{ matrix.slycot || 'no' }} Slycot;
      ${{ matrix.pandas || 'no' }} Pandas;
      ${{ matrix.cvxopt || 'no' }} CVXOPT
      ${{ matrix.array-and-matrix == 1 && '; array and matrix' || '' }}
      ${{ matrix.mplbackend && format('; {0}', matrix.mplbackend) }}
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.11']
        slycot: ["", "conda"]
        pandas: [""]
        cvxopt: ["", "conda"]
        mplbackend: [""]
        array-and-matrix: [0]
        include:
          - python-version: '3.11'
            slycot: conda
            pandas: conda
            cvxopt: conda
            mplbackend: QtAgg
            array-and-matrix: 1

    steps:
    - uses: actions/checkout@v3

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: test-env
        environment-file: .github/conda-env/test-env.yml
        miniforge-version: latest
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: false
        auto-activate-base: false

    - name: Install optional dependencies
      shell: bash -l {0}
      run: |
        if [[ '${{matrix.cvxopt}}' == 'conda' ]]; then
          mamba install cvxopt
        fi
        if [[ '${{matrix.slycot}}' == 'conda' ]]; then
          mamba install slycot
        fi
        if [[ '${{matrix.pandas}}' == 'conda' ]]; then
          mamba install pandas
        fi

    - name: Test with pytest
      shell: bash -l {0}
      env:
        PYTHON_CONTROL_ARRAY_AND_MATRIX: ${{ matrix.array-and-matrix }}
        MPLBACKEND: ${{ matrix.mplbackend }}
      run: pytest -v --cov=control --cov-config=.coveragerc control/tests

    - name: Coveralls parallel
      # https://github.com/coverallsapp/github-action
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true

  coveralls:
    name: coveralls completion
    needs: test-linux-conda
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
